<?php
/**
 * WooCommerce Order Conditions
 *
 * @package     ArrayPress\Conditions\Conditions\WooCommerce
 * @copyright   Copyright (c) 2026, ArrayPress Limited
 * @license     GPL-2.0-or-later
 * @since       1.0.0
 * @author      David Sherlock
 */

declare( strict_types=1 );

namespace ArrayPress\Conditions\Conditions\WooCommerce;

use ArrayPress\Conditions\Integrations\WooCommerce\Options;
use ArrayPress\Conditions\Integrations\WooCommerce\Order as OrderHelper;
use ArrayPress\Conditions\Operators;
use ArrayPress\Conditions\Options\Periods;

/**
 * Class Order
 *
 * Provides WooCommerce order conditions.
 */
class Order {

	/**
	 * Get all order conditions.
	 *
	 * @return array<string, array>
	 *
	 * @since 1.0.0
	 */
	public static function get_all(): array {
		$money    = __( 'Order: Money', 'arraypress' );
		$state    = __( 'Order: State', 'arraypress' );
		$items    = __( 'Order: Items', 'arraypress' );
		$customer = __( 'Order: Customer', 'arraypress' );

		return [
			// Money.
			'wc_order_total'               => [
				'label'         => __( 'Total', 'arraypress' ),
				'group'         => $money,
				'type'          => 'number',
				'placeholder'   => __( 'e.g. 100.00', 'arraypress' ),
				'min'           => 0,
				'step'          => 0.01,
				'description'   => __( 'The order total.', 'arraypress' ),
				'compare_value' => fn( $args ) => OrderHelper::get_total( $args ),
				'required_args' => [ 'order_id' ],
			],
			'wc_order_subtotal'            => [
				'label'         => __( 'Subtotal', 'arraypress' ),
				'group'         => $money,
				'type'          => 'number',
				'placeholder'   => __( 'e.g. 100.00', 'arraypress' ),
				'min'           => 0,
				'step'          => 0.01,
				'description'   => __( 'The order subtotal, before discounts, tax and shipping.', 'arraypress' ),
				'compare_value' => fn( $args ) => OrderHelper::get_subtotal( $args ),
				'required_args' => [ 'order_id' ],
			],
			'wc_order_tax'                 => [
				'label'         => __( 'Tax Amount', 'arraypress' ),
				'group'         => $money,
				'type'          => 'number',
				'placeholder'   => __( 'e.g. 20.00', 'arraypress' ),
				'min'           => 0,
				'step'          => 0.01,
				'description'   => __( 'Total tax on the order.', 'arraypress' ),
				'compare_value' => fn( $args ) => OrderHelper::get_tax( $args ),
				'required_args' => [ 'order_id' ],
			],
			'wc_order_shipping_total'      => [
				'label'         => __( 'Shipping Cost', 'arraypress' ),
				'group'         => $money,
				'type'          => 'number',
				'placeholder'   => __( 'e.g. 4.95', 'arraypress' ),
				'min'           => 0,
				'step'          => 0.01,
				'description'   => __( 'Shipping charged on the order.', 'arraypress' ),
				'compare_value' => fn( $args ) => OrderHelper::get_shipping_total( $args ),
				'required_args' => [ 'order_id' ],
			],
			'wc_order_discount'            => [
				'label'         => __( 'Discount Amount', 'arraypress' ),
				'group'         => $money,
				'type'          => 'number',
				'placeholder'   => __( 'e.g. 10.00', 'arraypress' ),
				'min'           => 0,
				'step'          => 0.01,
				'description'   => __( 'Total discount applied to the order.', 'arraypress' ),
				'compare_value' => fn( $args ) => OrderHelper::get_discount( $args ),
				'required_args' => [ 'order_id' ],
			],
			'wc_order_discount_percentage' => [
				'label'         => __( 'Discount (%)', 'arraypress' ),
				'group'         => $money,
				'type'          => 'number',
				'placeholder'   => __( 'e.g. 50', 'arraypress' ),
				'min'           => 0,
				'max'           => 100,
				'step'          => 0.1,
				'description'   => __( 'Discount as a share of the subtotal.', 'arraypress' ),
				'compare_value' => fn( $args ) => OrderHelper::get_discount_percentage( $args ),
				'required_args' => [ 'order_id' ],
			],
			'wc_order_refunded_total'      => [
				'label'         => __( 'Refunded Amount', 'arraypress' ),
				'group'         => $money,
				'type'          => 'number',
				'placeholder'   => __( 'e.g. 25.00', 'arraypress' ),
				'min'           => 0,
				'step'          => 0.01,
				'description'   => __( 'How much has been refunded against the order.', 'arraypress' ),
				'compare_value' => fn( $args ) => OrderHelper::get_refunded_total( $args ),
				'required_args' => [ 'order_id' ],
			],
			'wc_order_currency'            => [
				'label'         => __( 'Currency', 'arraypress' ),
				'group'         => $money,
				'type'          => 'select',
				'multiple'      => true,
				'placeholder'   => __( 'Select currency...', 'arraypress' ),
				'description'   => __( 'The currency the order was placed in.', 'arraypress' ),
				'options'       => Options::get_currencies(),
				'operators'     => Operators::collection_any_none(),
				'compare_value' => fn( $args ) => OrderHelper::get_currency( $args ),
				'required_args' => [ 'order_id' ],
			],

			// State.
			'wc_order_status'              => [
				'label'         => __( 'Status', 'arraypress' ),
				'group'         => $state,
				'type'          => 'select',
				'multiple'      => true,
				'placeholder'   => __( 'Select status...', 'arraypress' ),
				'description'   => __( 'The order status. Stored with a wc- prefix but compared without it, which is what WooCommerce returns.', 'arraypress' ),
				'options'       => Options::get_order_statuses(),
				'operators'     => Operators::collection_any_none(),
				'compare_value' => fn( $args ) => OrderHelper::get_status( $args ),
				'required_args' => [ 'order_id' ],
			],
			'wc_order_gateway'             => [
				'label'         => __( 'Payment Method', 'arraypress' ),
				'group'         => $state,
				'type'          => 'select',
				'multiple'      => true,
				'placeholder'   => __( 'Select gateway...', 'arraypress' ),
				'description'   => __( 'The gateway the order was paid through.', 'arraypress' ),
				'options'       => Options::get_gateways(),
				'operators'     => Operators::collection_any_none(),
				'compare_value' => fn( $args ) => OrderHelper::get_gateway( $args ),
				'required_args' => [ 'order_id' ],
			],
			'wc_order_is_paid'             => [
				'label'         => __( 'Paid', 'arraypress' ),
				'group'         => $state,
				'type'          => 'boolean',
				'description'   => __( 'Whether the order has reached a paid status.', 'arraypress' ),
				'compare_value' => fn( $args ) => OrderHelper::is_paid( $args ),
				'required_args' => [ 'order_id' ],
			],
			'wc_order_date_created'        => [
				'label'         => __( 'Date Created', 'arraypress' ),
				'group'         => $state,
				'type'          => 'date',
				'description'   => __( 'The date the order was placed.', 'arraypress' ),
				'compare_value' => fn( $args ) => OrderHelper::get_date_created( $args ),
				'required_args' => [ 'order_id' ],
			],
			'wc_order_date_paid'           => [
				'label'         => __( 'Date Paid', 'arraypress' ),
				'group'         => $state,
				'type'          => 'date',
				'description'   => __( 'The date the order was paid.', 'arraypress' ),
				'compare_value' => fn( $args ) => OrderHelper::get_date_paid( $args ),
				'required_args' => [ 'order_id' ],
			],
			'wc_order_age'                 => [
				'label'         => __( 'Age', 'arraypress' ),
				'group'         => $state,
				'type'          => 'number_unit',
				'placeholder'   => __( 'e.g. 7', 'arraypress' ),
				'min'           => 0,
				'units'         => Periods::get_age_units(),
				'description'   => __( 'How long ago the order was placed.', 'arraypress' ),
				'compare_value' => fn( $args ) => OrderHelper::get_age( $args ),
				'required_args' => [ 'order_id' ],
			],

			// Items.
			'wc_order_item_count'          => [
				'label'         => __( 'Total Items', 'arraypress' ),
				'group'         => $items,
				'type'          => 'number',
				'placeholder'   => __( 'e.g. 5', 'arraypress' ),
				'min'           => 0,
				'step'          => 1,
				'description'   => __( 'Total quantity across every line on the order.', 'arraypress' ),
				'compare_value' => fn( $args ) => OrderHelper::get_item_count( $args ),
				'required_args' => [ 'order_id' ],
			],
			'wc_order_unique_products'     => [
				'label'         => __( 'Distinct Products', 'arraypress' ),
				'group'         => $items,
				'type'          => 'number',
				'placeholder'   => __( 'e.g. 3', 'arraypress' ),
				'min'           => 0,
				'step'          => 1,
				'description'   => __( 'Number of distinct products on the order, ignoring quantities.', 'arraypress' ),
				'compare_value' => fn( $args ) => OrderHelper::get_unique_product_count( $args ),
				'required_args' => [ 'order_id' ],
			],
			'wc_order_products'            => [
				'label'         => __( 'Products', 'arraypress' ),
				'group'         => $items,
				'type'          => 'ajax',
				'multiple'      => true,
				'placeholder'   => __( 'Search products...', 'arraypress' ),
				'description'   => __( 'Whether specific products are on the order.', 'arraypress' ),
				'operators'     => Operators::collection(),
				'ajax'          => fn( ?string $search, ?array $ids ): array => Options::get_product_options( $search, $ids ),
				'compare_value' => fn( $args ) => OrderHelper::get_product_ids( $args ),
				'required_args' => [ 'order_id' ],
			],
			'wc_order_categories'          => [
				'label'         => __( 'Categories', 'arraypress' ),
				'group'         => $items,
				'type'          => 'term',
				'taxonomy'      => 'product_cat',
				'multiple'      => true,
				'placeholder'   => __( 'Search categories...', 'arraypress' ),
				'description'   => __( 'Categories of the products on the order.', 'arraypress' ),
				'operators'     => Operators::collection(),
				'compare_value' => fn( $args ) => OrderHelper::get_term_ids( $args, 'product_cat' ),
				'required_args' => [ 'order_id' ],
			],
			'wc_order_tags'                => [
				'label'         => __( 'Tags', 'arraypress' ),
				'group'         => $items,
				'type'          => 'term',
				'taxonomy'      => 'product_tag',
				'multiple'      => true,
				'placeholder'   => __( 'Search tags...', 'arraypress' ),
				'description'   => __( 'Tags of the products on the order.', 'arraypress' ),
				'operators'     => Operators::collection(),
				'compare_value' => fn( $args ) => OrderHelper::get_term_ids( $args, 'product_tag' ),
				'required_args' => [ 'order_id' ],
			],
			'wc_order_coupons'             => [
				'label'         => __( 'Coupons', 'arraypress' ),
				'group'         => $items,
				'type'          => 'ajax',
				'multiple'      => true,
				'placeholder'   => __( 'Search coupons...', 'arraypress' ),
				'description'   => __( 'Coupon codes used on the order.', 'arraypress' ),
				'operators'     => Operators::collection(),
				'ajax'          => fn( ?string $search, ?array $ids ): array => Options::get_coupon_options( $search, $ids ),
				'compare_value' => fn( $args ) => OrderHelper::get_coupons( $args ),
				'required_args' => [ 'order_id' ],
			],
			'wc_order_shipping_method'     => [
				'label'         => __( 'Shipping Method', 'arraypress' ),
				'group'         => $items,
				'type'          => 'select',
				'multiple'      => true,
				'placeholder'   => __( 'Select shipping method...', 'arraypress' ),
				'description'   => __( 'The shipping methods used on the order.', 'arraypress' ),
				'options'       => Options::get_shipping_methods(),
				'operators'     => Operators::collection(),
				'compare_value' => fn( $args ) => OrderHelper::get_shipping_methods( $args ),
				'required_args' => [ 'order_id' ],
			],

			// Customer.
			'wc_order_email'               => [
				'label'         => __( 'Email', 'arraypress' ),
				'group'         => $customer,
				'type'          => 'email',
				'placeholder'   => __( 'e.g. john@test.com, @gmail.com, .edu', 'arraypress' ),
				'description'   => __( 'The billing email on the order.', 'arraypress' ),
				'compare_value' => fn( $args ) => OrderHelper::get_email( $args ),
				'required_args' => [ 'order_id' ],
			],
			'wc_order_is_guest'            => [
				'label'         => __( 'Guest Order', 'arraypress' ),
				'group'         => $customer,
				'type'          => 'boolean',
				'description'   => __( 'Whether the order was placed without an account.', 'arraypress' ),
				'compare_value' => fn( $args ) => OrderHelper::is_guest( $args ),
				'required_args' => [ 'order_id' ],
			],
			'wc_order_user'                => [
				'label'         => __( 'User', 'arraypress' ),
				'group'         => $customer,
				'type'          => 'user',
				'multiple'      => true,
				'placeholder'   => __( 'Search users...', 'arraypress' ),
				'description'   => __( 'The user account the order belongs to.', 'arraypress' ),
				'operators'     => Operators::collection_any_none(),
				'compare_value' => fn( $args ) => OrderHelper::get_customer_id( $args ),
				'required_args' => [ 'order_id' ],
			],
			'wc_order_ip'                  => [
				'label'         => __( 'IP Address', 'arraypress' ),
				'group'         => $customer,
				'type'          => 'ip',
				'placeholder'   => __( 'e.g. 192.168.1.1, 192.168.1.0/24', 'arraypress' ),
				'description'   => __( 'The IP address recorded when the order was placed. Supports exact addresses, CIDR ranges, and wildcards.', 'arraypress' ),
				'compare_value' => fn( $args ) => OrderHelper::get_ip( $args ),
				'required_args' => [ 'order_id' ],
			],
			'wc_order_country'             => [
				'label'         => __( 'Billing Country', 'arraypress' ),
				'group'         => $customer,
				'type'          => 'select',
				'multiple'      => true,
				'placeholder'   => __( 'Select country...', 'arraypress' ),
				'description'   => __( 'The billing country on the order.', 'arraypress' ),
				'options'       => Options::get_countries(),
				'operators'     => Operators::collection_any_none(),
				'compare_value' => fn( $args ) => OrderHelper::get_country( $args ),
				'required_args' => [ 'order_id' ],
			],
			'wc_order_shipping_country'    => [
				'label'         => __( 'Shipping Country', 'arraypress' ),
				'group'         => $customer,
				'type'          => 'select',
				'multiple'      => true,
				'placeholder'   => __( 'Select country...', 'arraypress' ),
				'description'   => __( 'The shipping country on the order.', 'arraypress' ),
				'options'       => Options::get_countries(),
				'operators'     => Operators::collection_any_none(),
				'compare_value' => fn( $args ) => OrderHelper::get_shipping_country( $args ),
				'required_args' => [ 'order_id' ],
			],
			'wc_order_country_mismatch'    => [
				'label'         => __( 'Billing/Shipping Country Mismatch', 'arraypress' ),
				'group'         => $customer,
				'type'          => 'boolean',
				'description'   => __( 'Whether the billing and shipping countries differ. An order with no shipping country is not a mismatch — a virtual order never collects one.', 'arraypress' ),
				'compare_value' => fn( $args ) => OrderHelper::has_country_mismatch( $args ),
				'required_args' => [ 'order_id' ],
			],
			'wc_order_region'              => [
				'label'         => __( 'Billing State/Region', 'arraypress' ),
				'group'         => $customer,
				'type'          => 'text',
				'placeholder'   => __( 'e.g. CA', 'arraypress' ),
				'description'   => __( 'The billing state or region on the order.', 'arraypress' ),
				'operators'     => Operators::text_advanced(),
				'compare_value' => fn( $args ) => OrderHelper::get_region( $args ),
				'required_args' => [ 'order_id' ],
			],
			'wc_order_city'                => [
				'label'         => __( 'Billing City', 'arraypress' ),
				'group'         => $customer,
				'type'          => 'text',
				'placeholder'   => __( 'e.g. London', 'arraypress' ),
				'description'   => __( 'The billing city on the order.', 'arraypress' ),
				'operators'     => Operators::text_advanced(),
				'compare_value' => fn( $args ) => OrderHelper::get_city( $args ),
				'required_args' => [ 'order_id' ],
			],
			'wc_order_postcode'            => [
				'label'         => __( 'Billing Postcode', 'arraypress' ),
				'group'         => $customer,
				'type'          => 'text',
				'placeholder'   => __( 'e.g. SW1A', 'arraypress' ),
				'description'   => __( 'The billing postcode on the order.', 'arraypress' ),
				'operators'     => Operators::text_advanced(),
				'compare_value' => fn( $args ) => OrderHelper::get_postcode( $args ),
				'required_args' => [ 'order_id' ],
			],
			'wc_order_customer_note'       => [
				'label'         => __( 'Customer Note', 'arraypress' ),
				'group'         => $customer,
				'type'          => 'text',
				'placeholder'   => __( 'e.g. urgent', 'arraypress' ),
				'description'   => __( 'The note the customer left with the order.', 'arraypress' ),
				'operators'     => Operators::text_advanced(),
				'compare_value' => fn( $args ) => OrderHelper::get_customer_note( $args ),
				'required_args' => [ 'order_id' ],
			],

			// State — how the order came to exist, and what happened after.
			'wc_order_created_via'         => [
				'label'         => __( 'Created Via', 'arraypress' ),
				'group'         => $state,
				'type'          => 'select',
				'multiple'      => true,
				'placeholder'   => __( 'Select source...', 'arraypress' ),
				'description'   => __( 'How the order was created — checkout, the blocks Store API, the REST API, or the admin. An order created through the REST API on a store that only sells through its own checkout did not come from a customer.', 'arraypress' ),
				'options'       => Options::get_created_via_options(),
				'operators'     => Operators::collection_any_none(),
				'compare_value' => fn( $args ) => OrderHelper::get_created_via( $args ),
				'required_args' => [ 'order_id' ],
			],
			'wc_order_gateway_title'       => [
				'label'         => __( 'Payment Method Title', 'arraypress' ),
				'group'         => $state,
				'type'          => 'text',
				'placeholder'   => __( 'e.g. Credit Card', 'arraypress' ),
				'description'   => __( 'The payment method as shown to the customer, rather than its gateway ID.', 'arraypress' ),
				'operators'     => Operators::text_advanced(),
				'compare_value' => fn( $args ) => OrderHelper::get_gateway_title( $args ),
				'required_args' => [ 'order_id' ],
			],
			'wc_order_transaction_id'      => [
				'label'         => __( 'Transaction ID', 'arraypress' ),
				'group'         => $state,
				'type'          => 'text',
				'placeholder'   => __( 'e.g. ch_', 'arraypress' ),
				'description'   => __( 'The gateway\'s transaction reference. Empty until the order is paid.', 'arraypress' ),
				'operators'     => Operators::text_advanced(),
				'compare_value' => fn( $args ) => OrderHelper::get_transaction_id( $args ),
				'required_args' => [ 'order_id' ],
			],
			'wc_order_refund_count'        => [
				'label'         => __( 'Refund Count', 'arraypress' ),
				'group'         => $state,
				'type'          => 'number',
				'placeholder'   => __( 'e.g. 1', 'arraypress' ),
				'min'           => 0,
				'step'          => 1,
				'description'   => __( 'How many refunds have been recorded against the order. Several partial refunds is a different pattern from one full one.', 'arraypress' ),
				'compare_value' => fn( $args ) => OrderHelper::get_refund_count( $args ),
				'required_args' => [ 'order_id' ],
			],

			// Items — fulfilment shape.
			'wc_order_needs_shipping_address' => [
				'label'         => __( 'Needs Shipping Address', 'arraypress' ),
				'group'         => $items,
				'type'          => 'boolean',
				'description'   => __( 'Whether the order collects a shipping address at all.', 'arraypress' ),
				'compare_value' => fn( $args ) => OrderHelper::needs_shipping_address( $args ),
				'required_args' => [ 'order_id' ],
			],
			'wc_order_has_downloadable_item'  => [
				'label'         => __( 'Contains Downloadable Item', 'arraypress' ),
				'group'         => $items,
				'type'          => 'boolean',
				'description'   => __( 'Whether anything on the order is downloadable. Instant delivery leaves no window to cancel, so these orders carry more risk than physical ones.', 'arraypress' ),
				'compare_value' => fn( $args ) => OrderHelper::has_downloadable_item( $args ),
				'required_args' => [ 'order_id' ],
			],
			'wc_order_shipping_classes'       => [
				'label'         => __( 'Shipping Classes', 'arraypress' ),
				'group'         => $items,
				'type'          => 'select',
				'multiple'      => true,
				'placeholder'   => __( 'Select shipping class...', 'arraypress' ),
				'description'   => __( 'Shipping classes across the order\'s products.', 'arraypress' ),
				'options'       => Options::get_shipping_class_slugs(),
				'operators'     => Operators::collection(),
				'compare_value' => fn( $args ) => OrderHelper::get_shipping_classes( $args ),
				'required_args' => [ 'order_id' ],
			],
			'wc_order_tax_classes'            => [
				'label'         => __( 'Tax Classes', 'arraypress' ),
				'group'         => $items,
				'type'          => 'select',
				'multiple'      => true,
				'placeholder'   => __( 'Select tax class...', 'arraypress' ),
				'description'   => __( 'Tax classes across the order\'s products. WooCommerce stores the standard class as a blank slug; it is reported here as "standard" so a rule can name it.', 'arraypress' ),
				'options'       => Options::get_tax_class_slugs(),
				'operators'     => Operators::collection(),
				'compare_value' => fn( $args ) => OrderHelper::get_tax_classes( $args ),
				'required_args' => [ 'order_id' ],
			],

			// Customer — the rest of the address and the client behind it.
			'wc_order_user_agent'          => [
				'label'         => __( 'User Agent', 'arraypress' ),
				'group'         => $customer,
				'type'          => 'text',
				'placeholder'   => __( 'e.g. curl', 'arraypress' ),
				'description'   => __( 'The user agent recorded when the order was placed. Empty or scripted agents on a checkout order are worth a look.', 'arraypress' ),
				'operators'     => Operators::text_advanced(),
				'compare_value' => fn( $args ) => OrderHelper::get_user_agent( $args ),
				'required_args' => [ 'order_id' ],
			],
			'wc_order_phone'               => [
				'label'         => __( 'Billing Phone', 'arraypress' ),
				'group'         => $customer,
				'type'          => 'text',
				'placeholder'   => __( 'e.g. +44', 'arraypress' ),
				'description'   => __( 'The billing phone on the order.', 'arraypress' ),
				'operators'     => Operators::text_advanced(),
				'compare_value' => fn( $args ) => OrderHelper::get_phone( $args ),
				'required_args' => [ 'order_id' ],
			],
			'wc_order_company'             => [
				'label'         => __( 'Billing Company', 'arraypress' ),
				'group'         => $customer,
				'type'          => 'text',
				'placeholder'   => __( 'e.g. Acme Ltd', 'arraypress' ),
				'description'   => __( 'The billing company on the order.', 'arraypress' ),
				'operators'     => Operators::text_advanced(),
				'compare_value' => fn( $args ) => OrderHelper::get_company( $args ),
				'required_args' => [ 'order_id' ],
			],
			'wc_order_address'             => [
				'label'         => __( 'Billing Address', 'arraypress' ),
				'group'         => $customer,
				'type'          => 'text',
				'placeholder'   => __( 'e.g. PO Box', 'arraypress' ),
				'description'   => __( 'The first line of the billing address.', 'arraypress' ),
				'operators'     => Operators::text_advanced(),
				'compare_value' => fn( $args ) => OrderHelper::get_address( $args ),
				'required_args' => [ 'order_id' ],
			],
			'wc_order_shipping_region'     => [
				'label'         => __( 'Shipping State/Region', 'arraypress' ),
				'group'         => $customer,
				'type'          => 'text',
				'placeholder'   => __( 'e.g. CA', 'arraypress' ),
				'description'   => __( 'The shipping state or region on the order.', 'arraypress' ),
				'operators'     => Operators::text_advanced(),
				'compare_value' => fn( $args ) => OrderHelper::get_shipping_region( $args ),
				'required_args' => [ 'order_id' ],
			],
			'wc_order_shipping_city'       => [
				'label'         => __( 'Shipping City', 'arraypress' ),
				'group'         => $customer,
				'type'          => 'text',
				'placeholder'   => __( 'e.g. London', 'arraypress' ),
				'description'   => __( 'The shipping city on the order.', 'arraypress' ),
				'operators'     => Operators::text_advanced(),
				'compare_value' => fn( $args ) => OrderHelper::get_shipping_city( $args ),
				'required_args' => [ 'order_id' ],
			],
			'wc_order_shipping_postcode'   => [
				'label'         => __( 'Shipping Postcode', 'arraypress' ),
				'group'         => $customer,
				'type'          => 'text',
				'placeholder'   => __( 'e.g. SW1A', 'arraypress' ),
				'description'   => __( 'The shipping postcode on the order.', 'arraypress' ),
				'operators'     => Operators::text_advanced(),
				'compare_value' => fn( $args ) => OrderHelper::get_shipping_postcode( $args ),
				'required_args' => [ 'order_id' ],
			],
		];
	}
}
