<?php
/**
 * WooCommerce Product Conditions
 *
 * @package     ArrayPress\Conditions\Conditions\WooCommerce
 * @copyright   Copyright (c) 2026, ArrayPress Limited
 * @license     GPL-2.0-or-later
 * @since       1.0.0
 * @author      David Sherlock
 */

declare( strict_types=1 );

namespace ArrayPress\Conditions\Conditions\WooCommerce;

use ArrayPress\Conditions\Helpers\Parse;
use ArrayPress\Conditions\Integrations\WooCommerce\Options;
use ArrayPress\Conditions\Integrations\WooCommerce\Product as ProductHelper;
use ArrayPress\Conditions\Operators;
use ArrayPress\Conditions\Options\Periods;
use ArrayPress\Conditions\Options\WordPress;

/**
 * Class Product
 *
 * Provides WooCommerce product conditions.
 */
class Product {

	/**
	 * Get all product conditions.
	 *
	 * @return array<string, array>
	 *
	 * @since 1.0.0
	 */
	public static function get_all(): array {
		$details     = __( 'Product', 'arraypress' );
		$pricing     = __( 'Product: Pricing', 'arraypress' );
		$stock       = __( 'Product: Stock', 'arraypress' );
		$shipping    = __( 'Product: Shipping', 'arraypress' );
		$performance = __( 'Product: Performance', 'arraypress' );

		return [
			// Identity.
			'wc_product'                     => [
				'label'         => __( 'Product', 'arraypress' ),
				'group'         => $details,
				'type'          => 'ajax',
				'multiple'      => true,
				'placeholder'   => __( 'Search products...', 'arraypress' ),
				'description'   => __( 'Which product this is. Use "is any of" to name the products a rule applies to, or "is none of" to carve specific products out of a broader rule.', 'arraypress' ),
				'operators'     => Operators::collection_any_none(),
				'ajax'          => fn( ?string $search, ?array $ids ): array => Options::get_product_options( $search, $ids ),
				'compare_value' => fn( $args ) => ProductHelper::get_id_and_parent( $args ),
				'required_args' => [ 'product_id' ],
			],

			// Details.
			'wc_product_type'                => [
				'label'         => __( 'Type', 'arraypress' ),
				'group'         => $details,
				'type'          => 'select',
				'multiple'      => true,
				'placeholder'   => __( 'Select type...', 'arraypress' ),
				'description'   => __( 'Product type — simple, variable, grouped, external, or a type added by an extension.', 'arraypress' ),
				'options'       => Options::get_product_types(),
				'operators'     => Operators::collection_any_none(),
				'compare_value' => fn( $args ) => ProductHelper::get_type( $args ),
				'required_args' => [ 'product_id' ],
			],
			'wc_product_status'              => [
				'label'         => __( 'Status', 'arraypress' ),
				'group'         => $details,
				'type'          => 'select',
				'multiple'      => true,
				'placeholder'   => __( 'Select status...', 'arraypress' ),
				'description'   => __( 'The post status of the product.', 'arraypress' ),
				'options'       => WordPress::get_post_statuses(),
				'operators'     => Operators::collection_any_none(),
				'compare_value' => fn( $args ) => ProductHelper::get_status( $args ),
				'required_args' => [ 'product_id' ],
			],
			'wc_product_sku'                 => [
				'label'         => __( 'SKU', 'arraypress' ),
				'group'         => $details,
				'type'          => 'text',
				'placeholder'   => __( 'e.g. TSHIRT-', 'arraypress' ),
				'description'   => __( 'The product SKU.', 'arraypress' ),
				'operators'     => Operators::text_advanced(),
				'compare_value' => fn( $args ) => ProductHelper::get_sku( $args ),
				'required_args' => [ 'product_id' ],
			],
			'wc_product_author'              => [
				'label'         => __( 'Author', 'arraypress' ),
				'group'         => $details,
				'type'          => 'user',
				'multiple'      => true,
				'placeholder'   => __( 'Search users...', 'arraypress' ),
				'description'   => __( 'The author of the product.', 'arraypress' ),
				'operators'     => Operators::collection_any_none(),
				'compare_value' => fn( $args ) => ProductHelper::get_author( $args ),
				'required_args' => [ 'product_id' ],
			],
			'wc_product_date_created'        => [
				'label'         => __( 'Date Created', 'arraypress' ),
				'group'         => $details,
				'type'          => 'date',
				'description'   => __( 'The date the product was published.', 'arraypress' ),
				'compare_value' => fn( $args ) => ProductHelper::get_date_created( $args ),
				'required_args' => [ 'product_id' ],
			],
			'wc_product_date_modified'       => [
				'label'         => __( 'Date Modified', 'arraypress' ),
				'group'         => $details,
				'type'          => 'date',
				'description'   => __( 'The date the product was last modified.', 'arraypress' ),
				'compare_value' => fn( $args ) => ProductHelper::get_date_modified( $args ),
				'required_args' => [ 'product_id' ],
			],
			'wc_product_age'                 => [
				'label'         => __( 'Age', 'arraypress' ),
				'group'         => $details,
				'type'          => 'number_unit',
				'placeholder'   => __( 'e.g. 30', 'arraypress' ),
				'min'           => 0,
				'step'          => 1,
				'units'         => fn() => Periods::get_age_units(),
				'description'   => __( 'How long ago the product was published.', 'arraypress' ),
				'compare_value' => fn( $args ) => ProductHelper::get_age( $args ),
				'required_args' => [ 'product_id' ],
			],
			'wc_product_categories'          => [
				'label'         => __( 'Categories', 'arraypress' ),
				'group'         => $details,
				'type'          => 'term',
				'taxonomy'      => 'product_cat',
				'multiple'      => true,
				'placeholder'   => __( 'Search categories...', 'arraypress' ),
				'description'   => __( 'The categories assigned to the product.', 'arraypress' ),
				'operators'     => Operators::collection(),
				'compare_value' => fn( $args ) => ProductHelper::get_categories( $args ),
				'required_args' => [ 'product_id' ],
			],
			'wc_product_tags'                => [
				'label'         => __( 'Tags', 'arraypress' ),
				'group'         => $details,
				'type'          => 'term',
				'taxonomy'      => 'product_tag',
				'multiple'      => true,
				'placeholder'   => __( 'Search tags...', 'arraypress' ),
				'description'   => __( 'The tags assigned to the product.', 'arraypress' ),
				'operators'     => Operators::collection(),
				'compare_value' => fn( $args ) => ProductHelper::get_tags( $args ),
				'required_args' => [ 'product_id' ],
			],
			'wc_product_is_featured'         => [
				'label'         => __( 'Featured', 'arraypress' ),
				'group'         => $details,
				'type'          => 'boolean',
				'description'   => __( 'Whether the product is marked as featured.', 'arraypress' ),
				'compare_value' => fn( $args ) => ProductHelper::is_featured( $args ),
				'required_args' => [ 'product_id' ],
			],

			// Pricing.
			'wc_product_price'               => [
				'label'         => __( 'Price', 'arraypress' ),
				'group'         => $pricing,
				'type'          => 'number',
				'placeholder'   => __( 'e.g. 49.99', 'arraypress' ),
				'min'           => 0,
				'step'          => 0.01,
				'description'   => __( 'The active price — the sale price while one is running, otherwise the regular price.', 'arraypress' ),
				'compare_value' => fn( $args ) => ProductHelper::get_price( $args ),
				'required_args' => [ 'product_id' ],
			],
			'wc_product_regular_price'       => [
				'label'         => __( 'Regular Price', 'arraypress' ),
				'group'         => $pricing,
				'type'          => 'number',
				'placeholder'   => __( 'e.g. 49.99', 'arraypress' ),
				'min'           => 0,
				'step'          => 0.01,
				'description'   => __( 'The regular price, ignoring any sale.', 'arraypress' ),
				'compare_value' => fn( $args ) => ProductHelper::get_regular_price( $args ),
				'required_args' => [ 'product_id' ],
			],
			'wc_product_sale_price'          => [
				'label'         => __( 'Sale Price', 'arraypress' ),
				'group'         => $pricing,
				'type'          => 'number',
				'placeholder'   => __( 'e.g. 29.99', 'arraypress' ),
				'min'           => 0,
				'step'          => 0.01,
				'description'   => __( 'The sale price. Reports 0 when the product has no sale price set.', 'arraypress' ),
				'compare_value' => fn( $args ) => ProductHelper::get_sale_price( $args ),
				'required_args' => [ 'product_id' ],
			],
			'wc_product_discount_percentage' => [
				'label'         => __( 'Discount (%)', 'arraypress' ),
				'group'         => $pricing,
				'type'          => 'number',
				'placeholder'   => __( 'e.g. 50', 'arraypress' ),
				'min'           => 0,
				'max'           => 100,
				'step'          => 0.1,
				'description'   => __( 'How far the active price sits below the regular price.', 'arraypress' ),
				'compare_value' => fn( $args ) => ProductHelper::get_discount_percentage( $args ),
				'required_args' => [ 'product_id' ],
			],
			'wc_product_is_on_sale'          => [
				'label'         => __( 'On Sale', 'arraypress' ),
				'group'         => $pricing,
				'type'          => 'boolean',
				'description'   => __( 'Whether the product is currently on sale.', 'arraypress' ),
				'compare_value' => fn( $args ) => ProductHelper::is_on_sale( $args ),
				'required_args' => [ 'product_id' ],
			],
			'wc_product_is_free'             => [
				'label'         => __( 'Free', 'arraypress' ),
				'group'         => $pricing,
				'type'          => 'boolean',
				'description'   => __( 'Whether the product costs nothing.', 'arraypress' ),
				'compare_value' => fn( $args ) => ProductHelper::is_free( $args ),
				'required_args' => [ 'product_id' ],
			],
			'wc_product_tax_class'           => [
				'label'         => __( 'Tax Class', 'arraypress' ),
				'group'         => $pricing,
				'type'          => 'select',
				'multiple'      => true,
				'placeholder'   => __( 'Select tax class...', 'arraypress' ),
				'description'   => __( 'The tax class assigned to the product. WooCommerce stores the standard class as an empty slug.', 'arraypress' ),
				'options'       => Options::get_tax_classes(),
				'operators'     => Operators::collection_any_none(),
				'compare_value' => fn( $args ) => ProductHelper::get_tax_class( $args ),
				'required_args' => [ 'product_id' ],
			],
			'wc_product_tax_status'          => [
				'label'         => __( 'Tax Status', 'arraypress' ),
				'group'         => $pricing,
				'type'          => 'select',
				'multiple'      => true,
				'placeholder'   => __( 'Select tax status...', 'arraypress' ),
				'description'   => __( 'Whether the product is taxable, taxed on shipping only, or not taxed.', 'arraypress' ),
				'options'       => Options::get_tax_statuses(),
				'operators'     => Operators::collection_any_none(),
				'compare_value' => fn( $args ) => ProductHelper::get_tax_status( $args ),
				'required_args' => [ 'product_id' ],
			],

			// Stock.
			'wc_product_stock_quantity'      => [
				'label'         => __( 'Stock Quantity', 'arraypress' ),
				'group'         => $stock,
				'type'          => 'number',
				'placeholder'   => __( 'e.g. 5', 'arraypress' ),
				'step'          => 1,
				'description'   => __( 'Units in stock. Products that do not manage stock report 0, so pair this with "Manages Stock" when that distinction matters.', 'arraypress' ),
				'compare_value' => fn( $args ) => ProductHelper::get_stock_quantity( $args ),
				'required_args' => [ 'product_id' ],
			],
			'wc_product_stock_status'        => [
				'label'         => __( 'Stock Status', 'arraypress' ),
				'group'         => $stock,
				'type'          => 'select',
				'multiple'      => true,
				'placeholder'   => __( 'Select status...', 'arraypress' ),
				'description'   => __( 'In stock, out of stock, or on backorder.', 'arraypress' ),
				'options'       => Options::get_stock_statuses(),
				'operators'     => Operators::collection_any_none(),
				'compare_value' => fn( $args ) => ProductHelper::get_stock_status( $args ),
				'required_args' => [ 'product_id' ],
			],
			'wc_product_is_in_stock'         => [
				'label'         => __( 'In Stock', 'arraypress' ),
				'group'         => $stock,
				'type'          => 'boolean',
				'description'   => __( 'Whether the product is purchasable from stock.', 'arraypress' ),
				'compare_value' => fn( $args ) => ProductHelper::is_in_stock( $args ),
				'required_args' => [ 'product_id' ],
			],
			'wc_product_manages_stock'       => [
				'label'         => __( 'Manages Stock', 'arraypress' ),
				'group'         => $stock,
				'type'          => 'boolean',
				'description'   => __( 'Whether stock is tracked at product level.', 'arraypress' ),
				'compare_value' => fn( $args ) => ProductHelper::is_managing_stock( $args ),
				'required_args' => [ 'product_id' ],
			],
			'wc_product_is_on_backorder'     => [
				'label'         => __( 'On Backorder', 'arraypress' ),
				'group'         => $stock,
				'type'          => 'boolean',
				'description'   => __( 'Whether the product is currently on backorder.', 'arraypress' ),
				'compare_value' => fn( $args ) => ProductHelper::is_on_backorder( $args ),
				'required_args' => [ 'product_id' ],
			],
			'wc_product_sold_individually'   => [
				'label'         => __( 'Sold Individually', 'arraypress' ),
				'group'         => $stock,
				'type'          => 'boolean',
				'description'   => __( 'Whether the product is limited to one per order.', 'arraypress' ),
				'compare_value' => fn( $args ) => ProductHelper::is_sold_individually( $args ),
				'required_args' => [ 'product_id' ],
			],

			// Shipping — weight and dimensions.
			'wc_product_weight'              => [
				'label'         => __( 'Weight', 'arraypress' ),
				'group'         => $shipping,
				'type'          => 'number',
				'placeholder'   => __( 'e.g. 2.5', 'arraypress' ),
				'min'           => 0,
				'step'          => 0.01,
				'description'   => __( 'Product weight, in the store\'s configured weight unit.', 'arraypress' ),
				'compare_value' => fn( $args ) => ProductHelper::get_weight( $args ),
				'required_args' => [ 'product_id' ],
			],
			'wc_product_length'              => [
				'label'         => __( 'Length', 'arraypress' ),
				'group'         => $shipping,
				'type'          => 'number',
				'placeholder'   => __( 'e.g. 30', 'arraypress' ),
				'min'           => 0,
				'step'          => 0.01,
				'description'   => __( 'Product length, in the store\'s configured dimension unit.', 'arraypress' ),
				'compare_value' => fn( $args ) => ProductHelper::get_length( $args ),
				'required_args' => [ 'product_id' ],
			],
			'wc_product_width'               => [
				'label'         => __( 'Width', 'arraypress' ),
				'group'         => $shipping,
				'type'          => 'number',
				'placeholder'   => __( 'e.g. 20', 'arraypress' ),
				'min'           => 0,
				'step'          => 0.01,
				'description'   => __( 'Product width, in the store\'s configured dimension unit.', 'arraypress' ),
				'compare_value' => fn( $args ) => ProductHelper::get_width( $args ),
				'required_args' => [ 'product_id' ],
			],
			'wc_product_height'              => [
				'label'         => __( 'Height', 'arraypress' ),
				'group'         => $shipping,
				'type'          => 'number',
				'placeholder'   => __( 'e.g. 10', 'arraypress' ),
				'min'           => 0,
				'step'          => 0.01,
				'description'   => __( 'Product height, in the store\'s configured dimension unit.', 'arraypress' ),
				'compare_value' => fn( $args ) => ProductHelper::get_height( $args ),
				'required_args' => [ 'product_id' ],
			],
			'wc_product_longest_dimension'   => [
				'label'         => __( 'Longest Dimension', 'arraypress' ),
				'group'         => $shipping,
				'type'          => 'number',
				'placeholder'   => __( 'e.g. 120', 'arraypress' ),
				'min'           => 0,
				'step'          => 0.01,
				'description'   => __( 'The longest of the three dimensions. Carriers state oversize limits the same way, so this is usually the figure a shipping rule wants.', 'arraypress' ),
				'compare_value' => fn( $args ) => ProductHelper::get_longest_dimension( $args ),
				'required_args' => [ 'product_id' ],
			],
			'wc_product_volume'              => [
				'label'         => __( 'Volume', 'arraypress' ),
				'group'         => $shipping,
				'type'          => 'number',
				'placeholder'   => __( 'e.g. 6000', 'arraypress' ),
				'min'           => 0,
				'step'          => 0.01,
				'description'   => __( 'Length x width x height. Reports 0 when any dimension is unset, since a partial box has no meaningful volume.', 'arraypress' ),
				'compare_value' => fn( $args ) => ProductHelper::get_volume( $args ),
				'required_args' => [ 'product_id' ],
			],
			'wc_product_shipping_class'      => [
				'label'         => __( 'Shipping Class', 'arraypress' ),
				'group'         => $shipping,
				'type'          => 'select',
				'multiple'      => true,
				'placeholder'   => __( 'Select shipping class...', 'arraypress' ),
				'description'   => __( 'The shipping class assigned to the product.', 'arraypress' ),
				'options'       => Options::get_shipping_classes(),
				'operators'     => Operators::collection_any_none(),
				'compare_value' => fn( $args ) => (string) ProductHelper::get_shipping_class_id( $args ),
				'required_args' => [ 'product_id' ],
			],
			'wc_product_needs_shipping'      => [
				'label'         => __( 'Needs Shipping', 'arraypress' ),
				'group'         => $shipping,
				'type'          => 'boolean',
				'description'   => __( 'Whether the product has to be shipped.', 'arraypress' ),
				'compare_value' => fn( $args ) => ProductHelper::needs_shipping( $args ),
				'required_args' => [ 'product_id' ],
			],
			'wc_product_is_virtual'          => [
				'label'         => __( 'Virtual', 'arraypress' ),
				'group'         => $shipping,
				'type'          => 'boolean',
				'description'   => __( 'Whether the product is virtual.', 'arraypress' ),
				'compare_value' => fn( $args ) => ProductHelper::is_virtual( $args ),
				'required_args' => [ 'product_id' ],
			],
			'wc_product_is_downloadable'     => [
				'label'         => __( 'Downloadable', 'arraypress' ),
				'group'         => $shipping,
				'type'          => 'boolean',
				'description'   => __( 'Whether the product is downloadable.', 'arraypress' ),
				'compare_value' => fn( $args ) => ProductHelper::is_downloadable( $args ),
				'required_args' => [ 'product_id' ],
			],
			'wc_product_file_count'          => [
				'label'         => __( 'File Count', 'arraypress' ),
				'group'         => $shipping,
				'type'          => 'number',
				'placeholder'   => __( 'e.g. 1', 'arraypress' ),
				'min'           => 0,
				'step'          => 1,
				'description'   => __( 'How many downloadable files the product carries.', 'arraypress' ),
				'compare_value' => fn( $args ) => ProductHelper::get_file_count( $args ),
				'required_args' => [ 'product_id' ],
			],
			'wc_product_download_limit'      => [
				'label'         => __( 'Download Limit', 'arraypress' ),
				'group'         => $shipping,
				'type'          => 'number',
				'placeholder'   => __( 'e.g. 5', 'arraypress' ),
				'step'          => 1,
				'description'   => __( 'How many times a file may be downloaded. WooCommerce stores unlimited as -1.', 'arraypress' ),
				'compare_value' => fn( $args ) => ProductHelper::get_download_limit( $args ),
				'required_args' => [ 'product_id' ],
			],

			// Performance.
			'wc_product_total_sales'         => [
				'label'         => __( 'Total Sales', 'arraypress' ),
				'group'         => $performance,
				'type'          => 'number',
				'placeholder'   => __( 'e.g. 100', 'arraypress' ),
				'min'           => 0,
				'step'          => 1,
				'description'   => __( 'Lifetime units sold.', 'arraypress' ),
				'compare_value' => fn( $args ) => ProductHelper::get_total_sales( $args ),
				'required_args' => [ 'product_id' ],
			],
			'wc_product_average_rating'      => [
				'label'         => __( 'Average Rating', 'arraypress' ),
				'group'         => $performance,
				'type'          => 'number',
				'placeholder'   => __( 'e.g. 4.5', 'arraypress' ),
				'min'           => 0,
				'max'           => 5,
				'step'          => 0.1,
				'description'   => __( 'Average review rating, from 0 to 5.', 'arraypress' ),
				'compare_value' => fn( $args ) => ProductHelper::get_average_rating( $args ),
				'required_args' => [ 'product_id' ],
			],
			'wc_product_review_count'        => [
				'label'         => __( 'Review Count', 'arraypress' ),
				'group'         => $performance,
				'type'          => 'number',
				'placeholder'   => __( 'e.g. 10', 'arraypress' ),
				'min'           => 0,
				'step'          => 1,
				'description'   => __( 'How many reviews the product has.', 'arraypress' ),
				'compare_value' => fn( $args ) => ProductHelper::get_review_count( $args ),
				'required_args' => [ 'product_id' ],
			],

			// Details — catalogue and variations.
			'wc_product_catalog_visibility'  => [
				'label'         => __( 'Catalog Visibility', 'arraypress' ),
				'group'         => $details,
				'type'          => 'select',
				'multiple'      => true,
				'placeholder'   => __( 'Select visibility...', 'arraypress' ),
				'description'   => __( 'Where the product appears — shop, search, both, or hidden.', 'arraypress' ),
				'options'       => Options::get_catalog_visibilities(),
				'operators'     => Operators::collection_any_none(),
				'compare_value' => fn( $args ) => ProductHelper::get_catalog_visibility( $args ),
				'required_args' => [ 'product_id' ],
			],
			'wc_product_is_purchasable'      => [
				'label'         => __( 'Purchasable', 'arraypress' ),
				'group'         => $details,
				'type'          => 'boolean',
				'description'   => __( 'Whether the product can actually be bought. A product can be published and in stock and still not purchasable — a variable product with no price set is the usual case.', 'arraypress' ),
				'compare_value' => fn( $args ) => ProductHelper::is_purchasable( $args ),
				'required_args' => [ 'product_id' ],
			],
			'wc_product_reviews_allowed'     => [
				'label'         => __( 'Reviews Allowed', 'arraypress' ),
				'group'         => $details,
				'type'          => 'boolean',
				'description'   => __( 'Whether reviews are open on the product.', 'arraypress' ),
				'compare_value' => fn( $args ) => ProductHelper::is_reviews_allowed( $args ),
				'required_args' => [ 'product_id' ],
			],
			'wc_product_is_variation'        => [
				'label'         => __( 'Is Variation', 'arraypress' ),
				'group'         => $details,
				'type'          => 'boolean',
				'description'   => __( 'Whether this is a variation of a variable product rather than a product in its own right.', 'arraypress' ),
				'compare_value' => fn( $args ) => ProductHelper::is_variation( $args ),
				'required_args' => [ 'product_id' ],
			],
			'wc_product_parent'              => [
				'label'         => __( 'Parent Product', 'arraypress' ),
				'group'         => $details,
				'type'          => 'ajax',
				'multiple'      => true,
				'placeholder'   => __( 'Search products...', 'arraypress' ),
				'description'   => __( 'The parent product. Only a variation has one; everything else reports 0.', 'arraypress' ),
				'operators'     => Operators::collection_any_none(),
				'ajax'          => fn( ?string $search, ?array $ids ): array => Options::get_product_options( $search, $ids ),
				'compare_value' => fn( $args ) => ProductHelper::get_parent_id( $args ),
				'required_args' => [ 'product_id' ],
			],
			'wc_product_variation_count'     => [
				'label'         => __( 'Variation Count', 'arraypress' ),
				'group'         => $details,
				'type'          => 'number',
				'placeholder'   => __( 'e.g. 3', 'arraypress' ),
				'min'           => 0,
				'step'          => 1,
				'description'   => __( 'How many variations a variable product has. Anything that is not variable reports 0 — a simple product has no variations, it is not its own single variation.', 'arraypress' ),
				'compare_value' => fn( $args ) => ProductHelper::get_variation_count( $args ),
				'required_args' => [ 'product_id' ],
			],

			// Attributes — sizes, colours, and anything else the store defines.
			'wc_product_attribute'           => [
				'label'         => __( 'Attribute', 'arraypress' ),
				'group'         => __( 'Product: Attributes', 'arraypress' ),
				'type'          => 'text',
				'placeholder'   => __( 'pa_size:large', 'arraypress' ),
				'description'   => __( 'Match an attribute value. Format: attribute:value — for example `pa_size:large` or `pa_colour:black`. The attribute name is the taxonomy, with or without its pa_ prefix; the value is compared against every value the product carries for it.', 'arraypress' ),
				'compare_as'    => 'tags',
				'operators'     => Operators::tags_exact(),
				'user_value'    => fn( $value ) => Parse::meta( (string) $value )['value'],
				'compare_value' => fn( $args, $value ) => ProductHelper::get_attribute_from_rule( $args, $value ),
				'required_args' => [ 'product_id' ],
			],
			'wc_product_attribute_names'     => [
				'label'         => __( 'Has Attribute', 'arraypress' ),
				'group'         => __( 'Product: Attributes', 'arraypress' ),
				'type'          => 'select',
				'multiple'      => true,
				'placeholder'   => __( 'Select attribute...', 'arraypress' ),
				'description'   => __( 'Which global attributes the product carries, regardless of their values.', 'arraypress' ),
				'options'       => Options::get_attribute_taxonomies(),
				'operators'     => Operators::collection(),
				'compare_value' => fn( $args ) => ProductHelper::get_attribute_names( $args ),
				'required_args' => [ 'product_id' ],
			],
			'wc_product_attribute_count'     => [
				'label'         => __( 'Attribute Count', 'arraypress' ),
				'group'         => __( 'Product: Attributes', 'arraypress' ),
				'type'          => 'number',
				'placeholder'   => __( 'e.g. 2', 'arraypress' ),
				'min'           => 0,
				'step'          => 1,
				'description'   => __( 'How many attributes the product carries.', 'arraypress' ),
				'compare_value' => fn( $args ) => ProductHelper::get_attribute_count( $args ),
				'required_args' => [ 'product_id' ],
			],

			// Pricing — scheduled sales.
			'wc_product_sale_date_from'      => [
				'label'         => __( 'Sale Starts', 'arraypress' ),
				'group'         => $pricing,
				'type'          => 'date',
				'description'   => __( 'The date a scheduled sale begins. Blank when the sale has no schedule.', 'arraypress' ),
				'compare_value' => fn( $args ) => ProductHelper::get_sale_date_from( $args ),
				'required_args' => [ 'product_id' ],
			],
			'wc_product_sale_date_to'        => [
				'label'         => __( 'Sale Ends', 'arraypress' ),
				'group'         => $pricing,
				'type'          => 'date',
				'description'   => __( 'The date a scheduled sale ends. Blank when the sale has no schedule.', 'arraypress' ),
				'compare_value' => fn( $args ) => ProductHelper::get_sale_date_to( $args ),
				'required_args' => [ 'product_id' ],
			],

			// Stock — policy as well as level.
			'wc_product_backorders'          => [
				'label'         => __( 'Backorder Policy', 'arraypress' ),
				'group'         => $stock,
				'type'          => 'select',
				'multiple'      => true,
				'placeholder'   => __( 'Select policy...', 'arraypress' ),
				'description'   => __( 'What the product allows when stock runs out. Distinct from the stock status: a product set to allow backorders is only "on backorder" once its stock has actually gone.', 'arraypress' ),
				'options'       => Options::get_backorder_options(),
				'operators'     => Operators::collection_any_none(),
				'compare_value' => fn( $args ) => ProductHelper::get_backorders( $args ),
				'required_args' => [ 'product_id' ],
			],
			'wc_product_backorders_allowed'  => [
				'label'         => __( 'Backorders Allowed', 'arraypress' ),
				'group'         => $stock,
				'type'          => 'boolean',
				'description'   => __( 'Whether backorders are permitted at all, notified or otherwise.', 'arraypress' ),
				'compare_value' => fn( $args ) => ProductHelper::is_backorders_allowed( $args ),
				'required_args' => [ 'product_id' ],
			],
			'wc_product_low_stock_amount'    => [
				'label'         => __( 'Low Stock Threshold', 'arraypress' ),
				'group'         => $stock,
				'type'          => 'number',
				'placeholder'   => __( 'e.g. 2', 'arraypress' ),
				'min'           => 0,
				'step'          => 1,
				'description'   => __( 'The product\'s own low-stock threshold. Products without one report 0 and fall back to the store setting, which this does not read.', 'arraypress' ),
				'compare_value' => fn( $args ) => ProductHelper::get_low_stock_amount( $args ),
				'required_args' => [ 'product_id' ],
			],

			// Shipping — class by slug, and download terms.
			'wc_product_shipping_class_slug' => [
				'label'         => __( 'Shipping Class (Slug)', 'arraypress' ),
				'group'         => $shipping,
				'type'          => 'select',
				'multiple'      => true,
				'placeholder'   => __( 'Select shipping class...', 'arraypress' ),
				'description'   => __( 'The shipping class by slug, which is what a zone\'s rates are keyed on. Reads more clearly in a rule than the term ID does.', 'arraypress' ),
				'options'       => Options::get_shipping_class_slugs(),
				'operators'     => Operators::collection_any_none(),
				'compare_value' => fn( $args ) => ProductHelper::get_shipping_class( $args ),
				'required_args' => [ 'product_id' ],
			],
			'wc_product_download_expiry'     => [
				'label'         => __( 'Download Expiry', 'arraypress' ),
				'group'         => $shipping,
				'type'          => 'number',
				'placeholder'   => __( 'e.g. 30', 'arraypress' ),
				'step'          => 1,
				'description'   => __( 'How many days a download stays available. 0 means it never expires.', 'arraypress' ),
				'compare_value' => fn( $args ) => ProductHelper::get_download_expiry( $args ),
				'required_args' => [ 'product_id' ],
			],
		];
	}
}
